import{a as l,i as p}from"./assets/vendor-2dcf4ad5.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();l.defaults.headers.common["x-api-key"]="live_zeWygeVI9PjMBSUVH2oTp5elf4OEc1mdPIxnepILG4pvMCSXZXx1Q9oBRUMsYtTz";function u(){return l.get("https://api.thecatapi.com/v1/breeds").then(n=>n.data.map(t=>({name:t.name,id:t.id})))}function m(n){return l.get(`https://api.thecatapi.com/v1/images/search?breed_ids=${n}`).then(t=>{if(!t.data.length)throw new Error("Oops! Something went wrong!");const{url:i,breeds:o}=t.data[0];return{url:i,description:o[0].description,name:o[0].name,temperament:o[0].temperament}})}const c=document.querySelector(".breed-select"),d=document.querySelector(".loader"),a=document.querySelector(".cat-info");c.addEventListener("input",f);u().then(n=>{c.innerHTML=n.map(t=>`<option value="${t.id}">${t.name}</option>`).join(""),c.classList.remove("hidden")}).catch(n=>{p.show({message:"Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"#FCE8E6"})}).finally(()=>{d.classList.add("hidden")});function f(n){const t=n.target.value;d.classList.remove("hidden"),m(t).then(({url:i,description:o,name:e,temperament:r})=>{a.innerHTML=`
        <img src="${i}" alt="a cat of ${e} breed" width="500px" />
        <div class="div-text">
            <h2 class="title">${e}</h2>
            <p class="text">${o}</p>
            <p class="text"><span class="temp">Temperament: </span>${r}</p>
        </div>
      `,a.classList.remove("hidden")}).catch(i=>{p.show({message:"Oops! Something went wrong! Try reloading the page!",position:"topCenter",color:"#FCE8E6"}),a.classList.add("hidden")}).finally(()=>{d.classList.add("hidden")})}
//# sourceMappingURL=commonHelpers.js.map
